In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/processed/cleaned_financial_data.csv")
df.head()

,Transaction_ID,Transaction_Date,Company_Code,Cost_Center,Profit_Center,Account_Category,Transaction_Type,Amount,Budget,Payment_Status,Description,Quantity,Department,Currency,Invoice_ID,Vendor_ID,Tax_Amount,Profit,Approval_Status,Anomaly_Indicator
0,TX005450,01-17-2024,C003,CC107,PC206,Procurement,Expense,660134.88,870600.30,Pending,Raw material procurement,653.0,Procurement,INR,INV-2024-04285,NaN,115121.44,NaN,Approved,0
1,TX000061,01-21-2021,C001,CC111,PC202,Marketing,Expense,226317.84,255507.62,Paid,Marketing campaign,1.0,Sales,INR,INV-2021-00045,V040,42898.57,NaN,Approved,0
2,TX007730,02-10-2025,C002,CC105,PC206,Marketing,Expense,381300.39,427732.69,Partially Paid,Trade show sponsorship,1.0,Marketing,INR,INV-2025-06066,V035,70826.38,NaN,Approved,0
3,TX003695,02-14-2023,C002,CC112,PC204,Procurement,Expense,352712.21,360120.03,Partially Paid,Software license purchase,319.0,Operations,INR,INV-2023-02901,V001,62394.66,NaN,Approved,0
4,TX001800,02-25-2022,C005,CC104,PC206,Sales,Revenue,599713.69,603576.07,Paid,Product sales revenue,450.0,Sales,INR,INV-2022-01433,NaN,109719.59,164961.87,Pending,0

In [5]:
df.shape

(9802, 20)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9802 entries, 0 to 9801
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Transaction_ID     9802 non-null   object
 1   Transaction_Date   9802 non-null   object
 2   Company_Code       9802 non-null   object
 3   Cost_Center        9802 non-null   object
 4   Profit_Center      9802 non-null   object
 5   Account_Category   9802 non-null   object
 6   Transaction_Type   9802 non-null   object
 7   Amount             9802 non-null   float64
 8   Budget             9802 non-null   float64
 9   Payment_Status     9802 non-null   object
 10  Description        9802 non-null   object
 11  Quantity           9802 non-null   float64
 12  Department         9802 non-null   object
 13  Currency           9802 non-null   object
 14  Invoice_ID         7649 non-null   object
 15  Vendor_ID          5107 non-null   object
 16  Tax_Amount         9802 non-null   float64
 17  Profit             1547 non-null   float64
 18  Approval_Status    9802 non-null   object
 19  Anomaly_Indicator  9802 non-null   int64
dtypes: float64(5), int64(1), object(14)
memory usage: 1.5+ MB

In [10]:
df["Transaction_Date"] = pd.to_datetime(
    df["Transaction_Date"],
    format="mixed",
    dayfirst=True
)

In [17]:
df["Year"] = df["Transaction_Date"].dt.year

In [18]:
df["Month"] = df["Transaction_Date"].dt.month

In [19]:
df["Quarter"] = df["Transaction_Date"].dt.quarter

In [20]:
df[["Transaction_Date", "Year", "Month", "Quarter"]].head(10)

  Transaction_Date  Year  Month  Quarter
0       2024-01-17  2024      1        1
1       2021-01-21  2021      1        1
2       2025-10-02  2025     10        4
3       2023-02-14  2023      2        1
4       2022-02-25  2022      2        1
5       2024-09-02  2024      9        3
6       2022-04-03  2022      4        2
7       2025-04-27  2025      4        2
8       2022-11-04  2022     11        4
9       2023-12-04  2023     12        4

In [21]:
df[["Year", "Month", "Quarter"]].nunique()

Year        5
Month      12
Quarter     4
dtype: int64

In [22]:
df["Budget_Variance"] = df["Amount"] - df["Budget"]

In [23]:
df[["Amount", "Budget", "Budget_Variance"]].head(10)

      Amount     Budget  Budget_Variance
0  660134.88  870600.30       -210465.42
1  226317.84  255507.62        -29189.78
2  381300.39  427732.69        -46432.30
3  352712.21  360120.03         -7407.82
4  599713.69  603576.07         -3862.38
5   70076.65   77205.87         -7129.22
6  167587.77  181150.06        -13562.29
7  209629.73  249186.29        -39556.56
8   37386.31   44326.22         -6939.91
9  151468.87  156218.85         -4749.98

In [24]:
df["Budget_Utilization"] = (
    df["Amount"] / df["Budget"]
) * 100

In [25]:
df[["Amount", "Budget", "Budget_Utilization"]].head(10)

      Amount     Budget  Budget_Utilization
0  660134.88  870600.30           75.825253
1  226317.84  255507.62           88.575769
2  381300.39  427732.69           89.144552
3  352712.21  360120.03           97.942958
4  599713.69  603576.07           99.360084
5   70076.65   77205.87           90.765961
6  167587.77  181150.06           92.513229
7  209629.73  249186.29           84.125708
8   37386.31   44326.22           84.343556
9  151468.87  156218.85           96.959407

In [26]:
df["Budget"].eq(0).sum()

0

In [27]:
df["Budget_Variance"].describe()

count    9.802000e+03
mean     9.628952e+03
std      2.938389e+05
min     -8.859848e+05
25%     -2.220716e+04
50%     -3.634560e+03
75%      6.007618e+03
max      9.536728e+06
Name: Budget_Variance, dtype: float64

In [28]:
df["Budget_Variance"].head(10)

0   -210465.42
1    -29189.78
2    -46432.30
3     -7407.82
4     -3862.38
5     -7129.22
6    -13562.29
7    -39556.56
8     -6939.91
9     -4749.98
Name: Budget_Variance, dtype: float64

In [29]:
df["Budget_Utilization"].describe()

count    9802.000000
mean      106.997192
std        80.602396
min         5.676282
25%        86.669376
50%        95.487748
75%       106.633035
max      1648.530383
Name: Budget_Utilization, dtype: float64

In [30]:
df["Budget_Utilization"].head(10)

0    75.825253
1    88.575769
2    89.144552
3    97.942958
4    99.360084
5    90.765961
6    92.513229
7    84.125708
8    84.343556
9    96.959407
Name: Budget_Utilization, dtype: float64

In [31]:
df.isnull().sum()

Transaction_ID           0
Transaction_Date         0
Company_Code             0
Cost_Center              0
Profit_Center            0
Account_Category         0
Transaction_Type         0
Amount                   0
Budget                   0
Payment_Status           0
Description              0
Quantity                 0
Department               0
Currency                 0
Invoice_ID            2153
Vendor_ID             4695
Tax_Amount               0
Profit                8255
Approval_Status          0
Anomaly_Indicator        0
Year                     0
Month                    0
Quarter                  0
Budget_Variance          0
Budget_Utilization       0
dtype: int64

In [32]:
df.shape

(9802, 25)

In [33]:
df.columns.tolist()

['Transaction_ID',
 'Transaction_Date',
 'Company_Code',
 'Cost_Center',
 'Profit_Center',
 'Account_Category',
 'Transaction_Type',
 'Amount',
 'Budget',
 'Payment_Status',
 'Description',
 'Quantity',
 'Department',
 'Currency',
 'Invoice_ID',
 'Vendor_ID',
 'Tax_Amount',
 'Profit',
 'Approval_Status',
 'Anomaly_Indicator',
 'Year',
 'Month',
 'Quarter',
 'Budget_Variance',
 'Budget_Utilization']

In [34]:
df.to_csv(
    "../data/processed/financial_data_features.csv",
    index=False
)